dist: bionic
language: node_js
node_js:
  - 10
  - 12
  - 14
  - node

env:
  global:
    # Use node_modules to cache the downloaded browsers: https://github.com/microsoft/playwright/blob/98cc9db8e888aa1f32c06fd73abd9a7135f83fe8/docs/ci.md#caching-browsers
    - PLAYWRIGHT_BROWSERS_PATH=0

addons:
  apt:
    packages:
      # This is required to run chromium
      - libgbm1

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
